### ISSUE TITLE
Count lines of code?

### ISSUE THREAD

**Issue by ericphanson** [giordano/AnalyzeRegistry.jl#8]
I think it would be interesting to see things like the distribution of # of LoC over packages in General, or count the total LoC in a registry. To be extra informative, we could do four counts: `src`, `test`, `docs`, and the whole directory (in case there are interesting files in other folders).

I've used `tokei` before and it's really fast and seems quite accurate, and can count Julia code, markdown, etc, and can output JSON or other structured data. So using that, we could either hold counts for common things (like Julia code / markdown / comments) in our own data structure, or just hold onto the JSON blobs in the `Package` and query them later on.

What do you think?

**Comment by giordano** [comment]
Good idea!  (building a Rust package with BinaryBuilder may not be super-easy at the moment though :eyes:)

**Comment by ericphanson** [comment]
what's broken with BB rust right now? I think for `tokei` the easiest way might be to just use the CLI so I don't have to write rust bindings, and that might avoid linking issues if that's the problem

**Comment by giordano** [comment]
> what's broken with BB rust right now?

It doesn't work very well at the moment.  You can try, but it may not work in some cases (we don't have many datapoints, but yesterday I found a broken package)
